name: sage unit tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
        run: go build -v ./...
        -name: Test